<!DOCTYPE html>
<html>
    <head>
        <title> </title>
    </head>
    <body>
<?php 
$c1 = 
["imageName" => "",
"score" => "1",
"suit" => "clubs"];
$c2 = 
["imageName" => "",
"score" => "2",
"suit" => "clubs"];
$c3 = 
["imageName" => "",
"score" => "3",
"suit" => "clubs"];
$c4 = 
["imageName" => "",
"score" => "4",
"suit" => "clubs"];
$c5 = 
["imageName" => "",
"score" => "5",
"suit" => "clubs"];
$c6 = 
["imageName" => "",
"score" => "6",
"suit" => "clubs"];
$c7 = 
["imageName" => "",
"score" => "7",
"suit" => "clubs"];
$c8 = 
["imageName" => "",
"score" => "8",
"suit" => "clubs"];
$c9 = 
["imageName" => "",
"score" => "9",
"suit" => "clubs"];
$c10 = 
["imageName" => "",
"score" => "10",
"suit" => "clubs"];
$cJ = 
["imageName" => "",
"score" => "11",
"suit" => "clubs"];
$cQ = 
["imageName" => "",
"score" => "12",
"suit" => "clubs"];
$cK = 
["imageName" => "",
"score" => "13",
"suit" => "clubs"];
$cA = 
["imageName" => "",
"score" => "1",
"suit" => "clubs"];


//spades
$s1 = 
["imageName" => "",
"score" => "1",
"suit" => "spades"];
$s2 = 
["imageName" => "",
"score" => "2",
"suit" => "spades"];
$s3 = 
["imageName" => "",
"score" => "3",
"suit" => "spades"];
$s4 = 
["imageName" => "",
"score" => "4",
"suit" => "spades"];
$s5 = 
["imageName" => "",
"score" => "5",
"suit" => "spades"];
$s6 = 
["imageName" => "",
"score" => "6",
"suit" => "spades"];
$s7 = 
["imageName" => "",
"score" => "7",
"suit" => "spades"];
$s8 = 
["imageName" => "",
"score" => "8",
"suit" => "spades"];
$s9 = 
["imageName" => "",
"score" => "9",
"suit" => "spades"];
$s10 = 
["imageName" => "",
"score" => "10",
"suit" => "spades"];
$sJ = 
["imageName" => "",
"score" => "11",
"suit" => "spades"];
$sQ = 
["imageName" => "",
"score" => "12",
"suit" => "spades"];
$sK = 
["imageName" => "",
"score" => "13",
"suit" => "spades"];
$sA = 
["imageName" => "",
"score" => "1",
"suit" => "spades"];

// hearts
$h1 = 
["imageName" => "",
"score" => "1",
"suit" => "hearts"];
$h2 = 
["imageName" => "",
"score" => "2",
"suit" => "hearts"];
$h3 = 
["imageName" => "",
"score" => "3",
"suit" => "hearts"];
$h4 = 
["imageName" => "",
"score" => "4",
"suit" => "hearts"];
$h5 = 
["imageName" => "",
"score" => "5",
"suit" => "hearts"];
$h6 = 
["imageName" => "",
"score" => "6",
"suit" => "hearts"];
$h7 = 
["imageName" => "",
"score" => "7",
"suit" => "hearts"];
$h8 = 
["imageName" => "",
"score" => "8",
"suit" => "hearts"];
$h9 = 
["imageName" => "",
"score" => "9",
"suit" => "hearts"];
$h10 = 
["imageName" => "",
"score" => "10",
"suit" => "hearts"];
$hJ = 
["imageName" => "",
"score" => "11",
"suit" => "hearts"];
$hQ = 
["imageName" => "",
"score" => "12",
"suit" => "hearts"];
$hK = 
["imageName" => "",
"score" => "13",
"suit" => "hearts"];
$hA = 
["imageName" => "",
"score" => "1",
"suit" => "hearts"];

//diamonds
$d1 = 
["imageName" => "",
"score" => "1",
"suit" => "diamonds"];
$d2 = 
["imageName" => "",
"score" => "2",
"suit" => "diamonds"];
$d3 = 
["imageName" => "",
"score" => "3",
"suit" => "diamonds"];
$d4 = 
["imageName" => "",
"score" => "4",
"suit" => "diamonds"];
$d5 = 
["imageName" => "",
"score" => "5",
"suit" => "diamonds"];
$d6 = 
["imageName" => "",
"score" => "6",
"suit" => "diamonds"];
$d7 = 
["imageName" => "",
"score" => "7",
"suit" => "diamonds"];
$d8 = 
["imageName" => "",
"score" => "8",
"suit" => "diamonds"];
$d9 = 
["imageName" => "",
"score" => "9",
"suit" => "diamonds"];
$d10 = 
["imageName" => "",
"score" => "10",
"suit" => "diamonds"];
$dJ = 
["imageName" => "",
"score" => "11",
"suit" => "diamonds"];
$dQ = 
["imageName" => "",
"score" => "12",
"suit" => "diamonds"];
$dK = 
["imageName" => "",
"score" => "13",
"suit" => "diamonds"];
$dA = 
["imageName" => "",
"score" => "1",
"suit" => "diamonds"];

$deck=[$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8, $c9, $c10, $cJ, $cQ, $cK, $cA, $s1,$s2,$s3,$s4,$s5,$s6,$s7,$s8, $s9, $s10, $sJ, $sQ, $sK, $sA, $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8, $d9, $d10, $dJ, $dQ, $dK, $dA, $h1,$h2,$h3,$h4,$h5,$h6,$h7,$h8, $h9, $h10, $hJ, $hQ, $hK, $hA];


?>
    </body>
</html>